"""Static Agent-runtime environment allowlist; it carries no secret values."""

from __future__ import annotations


AGENT_ENV_ALLOWLIST = frozenset({
    "HOME", "PATH", "PYTHONPATH", "TMPDIR", "TMP", "TEMP", "LANG", "LC_ALL",
    "USER", "LOGNAME",
    "OPENAI_BASE_URL", "OPENAI_API_KEY",
    "ANTHROPIC_BASE_URL", "ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN",
    "RESBENCH_LLM_BASE_URL", "RESBENCH_LLM_API_KEY", "RESBENCH_MCP_TOKEN", "RESBENCH_HARNESS_CHANNEL_TOKEN",
    "RESBENCH_K8S_MCP_URL", "RESBENCH_TELEMETRY_MCP_URL", "RESBENCH_SOURCE_MCP_URL",
    "RESBENCH_CHAOS_CONTROL_MCP_URL", "RESBENCH_HARNESS_CHANNEL_MCP_URL",
    "RESBENCH_COROOT_MCP_URL", "RESBENCH_CHAOS_MESH_CONTROL_MCP_URL", "RESBENCH_CODE_SANDBOX_MCP_URL",
    "RESBENCH_BLADEAI_K8S_MCP_SSE_URL", "RESBENCH_BLADEAI_TELEMETRY_MCP_SSE_URL",
    "RESBENCH_BLADEAI_SOURCE_MCP_SSE_URL", "RESBENCH_BLADEAI_CHAOS_CONTROL_MCP_SSE_URL",
    "RESBENCH_BLADEAI_HARNESS_CHANNEL_MCP_SSE_URL", "RESBENCH_BLADEAI_COROOT_MCP_SSE_URL",
    "RESBENCH_BLADEAI_CHAOS_MESH_CONTROL_MCP_SSE_URL", "RESBENCH_BLADEAI_CODE_SANDBOX_MCP_SSE_URL",
    "RESBENCH_TRIAL_NAMESPACE",
    "RESBENCH_BLADE_SHIM_STATE_FILE", "BLADE_AI_BLADE_PATH", "BLADE_AI_KUBECTL_PATH", "BLADE_AI_KUBECONFIG_PATH",
    "BLADE_AI_MEMORY_DIR", "BLADE_AI_LLM_API_KEY", "BLADE_AI_API_BASE_URL",
    "BLADE_AI_MODEL_NAME", "BLADE_AI_MCP_ENABLED", "BLADE_AI_MCP_CONFIG_PATH",
    "STAGE2_BLADEAI_MODEL", "STAGE2_BLADEAI_PYTHON", "CODEX_HOME", "CLAUDE_CONFIG_DIR",
    "DSH_HOME", "DSH_TOOLS_MODE", "XDG_CONFIG_HOME", "XDG_CACHE_HOME", "NO_COLOR",
})
